### ISSUE TITLE
Extension doesn't work for new code

### ISSUE THREAD

**Issue by rafistrauss** [coderfin/logical-properties#1]
Love the extension idea! 

Seems to be a bug where the extension only works for the current editor window upon VSCode start/reload

Screenshots: 
![image](https://user-images.githubusercontent.com/4576234/148100675-67d18edd-9e5c-48d6-a9d1-4e3b089d33a0.png)

![image](https://user-images.githubusercontent.com/4576234/148100815-7b1e1fd6-f009-4ee8-851a-68ae6ceb4ec3.png)

Log message:
`[2022-01-04 12:31:19.699] [exthost] [warning] coderfin.logical-properties - Code actions of kind 'source.fixAll 'requested but returned code action is of kind 'quickfix'. Code action will be dropped. Please check 'CodeActionContext.only' to only return requested code actions.`

**Comment by coderfin** [comment]
Thanks for the feedback @rafistrauss!

I have resolved this issue in version 0.1.9.  
https://marketplace.visualstudio.com/_apis/public/gallery/publishers/coderfin/vsextensions/logical-properties/0.1.9/vspackage


It looks like the log message may be another unrelated issue but I'm not sure.  If you continue to experience problems feel free to reopen this issue or create a new issue.

Thanks again!
