### ISSUE TITLE
[Feature Request]: Ignore specific CSS properties

### ISSUE THREAD

**Issue by patriziosotgiu** [coderfin/logical-properties#14]
Hi, and thanks for the helpful extension!

This is more of an idea/feature request.
It would be great to have a setting to ignore specific properties. 

I'm working on a project where we don't replace some properties with their respective logical ones (e.g., `min-width,` `max-width`)

Having an ignore list would help reduce the warnings in the problems list and leverage the replacement of all functionality more efficiently.

**Comment by coderfin** [comment]
@patriziosotgiu 

I just released a new version that adds a configuration setting called `ignoreList` that lets you ignore certain css properties.  Install the update and let me know what you think.
