### ISSUE TITLE
Add setting for ignore languages.

### ISSUE THREAD

**Issue by rcclerigo** [coderfin/logical-properties#18]
This extension is fantastic. Can you / others add a setting to ignore specific languages? For example in Typescript i regularly use DOMRect values with top, left, bottom which I can't easily change, so it would be great to not get warnings in those files.

**Comment by coderfin** [comment]
@rcclerigo 

I just released a new version (v0.1.15) that adds a configuration setting called `ignoreLanguageIds` that lets you ignore certain files by language identifier.  See: https://code.visualstudio.com/docs/languages/identifiers#_known-language-identifiers

Install the update and let me know what you think.

If you have the chance to leave a [review](https://marketplace.visualstudio.com/items?itemName=coderfin.logical-properties&ssr=false#review-details) and you haven't already it would be much appreciated.

**Comment by rcclerigo** [comment]
It works great! thank you!
