### ISSUE TITLE
Ignoring media queries

### ISSUE THREAD

**Issue by stephenmcghee** [coderfin/logical-properties#4]
First off, thank you for creating this plugin, its very useful!

I have a request. When replacing all physical properties in a stylesheet with logical equivalents, is there a way to ignore media queries?
Logical properties aren't supported in media queries.

**This works:**
`@media (min-width: 992px)`
**This doesn't:**
`@media (min-inline-size: 992px)`

**Comment by coderfin** [comment]
Good catch!  I think I can make that happen.  Thanks for reporting.  I'll let you know when the fix has been made.

**Comment by hansgrimm** [comment]
Still waiting for this :)

**Comment by coderfin** [comment]
@stephenmcghee 
@hansgrimm 

I just released a new version that ignores media queries.  Install the update and let me know what you think.

Also, if you want to ignore a certain css property you can add it to the `ignoreList` now.  See #14
