### ISSUE TITLE
[Not an Issue] Question about logical properties

### ISSUE THREAD

**Issue by MariusMeeren** [coderfin/logical-properties#5]
**Hi!**

I can probably just google my way to the solution to my question, but I'll ask here instead.
Is there something about logical properties that makes it a better than physical properties?

And also, I assume the properties is doing the exact same thing, they are just written differently.

Anyways, I can use the extension you made, but one thing that could be great is to have a toggleable function that by default is off, where everytime the extension fixes a property and makes it logical, it adds a comment after the property saying what the physical equivalent is. 

If I enable the function, it does this:

`left: 60px; -> inset-inline-start: 60px; /* left: 60px; */`

If there is a reason behind using logical properties over physical, I would love to use logical. To keep my code fresh and learn more!
But then going over my code again with these new logical properties. I just cannot understand what is what. And for me it kind of ruins my code as I am not familiar with logical properties. 

I literally just heard about it today, like 20 minutes ago 💯

**Comment by coderfin** [comment]
Great questions.
I'm going to leave the research and learning up to you this time.

As far as adding a comment, that is outside of the scope of what I can work on right now.  If you feel inclined you are welcome to create a PR.
