### ISSUE TITLE
Showing wrong suggestion for border-radius case

### ISSUE THREAD

**Issue by EswaramoorthyKarthikeyan** [coderfin/logical-properties#8]
For `border-top-right-radius` it suggesting `border-end-start-radius` actually it is `border-bottom-left-radius` but is should suggest `border-start-end-radius`.

<img width="677" alt="Screenshot 2023-11-06 at 11 45 31 PM" src="https://github.com/coderfin/logical-properties/assets/29886442/75133958-a45a-4387-a627-dd2fbd124f5a">
`

**Comment by coderfin** [comment]
Fixed in #7 
Fixed in #9
